# Pre-commit hooks for Rust project
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code with cargo fmt
        entry: cargo fmt
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust code with cargo clippy
        entry: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
        args: ["--all-targets", "--all-features", "--", "-D", "warnings"]

      - id: cargo-check
        name: cargo check
        description: Check Rust code with cargo check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
        args: ["--all-targets", "--all-features"]

      - id: cargo-test
        name: cargo test
        description: Run Rust tests
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-push]